[tool.poetry]
name = "b√§ckerone"
version = "0.1.0"
description = ""
authors = ["Iamjava <jan.vaorin@tu-dortmund.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
